### ISSUE TITLE
Prediction on Ade20k and coco_stuff

### ISSUE THREAD

**Issue by achreff** [mseg-dataset/mseg-semantic#1]
First thank you for the wonderful work
I have some suggestion:
you can add to requirement.txt the package(Apex, Yaml and yacs). 

I have question: even i change the model from Mseg 3m to coco-panoptic-133-1m or ade20k-150 the output are the same.  haw i can excute the prediction on coco stuff with output 182 class and ade20k with 150 class

Best regards

**Comment by johnwlambert** [comment]
Thanks for your interest in our work @achreff. Thanks for noting those dependencies, I'm still standing up the repo dependencies/unit tests/Colab, will take me maybe by early next week to finalize.

Good note about the output number of classes for each of those models. While the number of output classes are identical, the output (i.e. predictions) certainly will not be the same.

When we train a baseline model on a single dataset, we train it in the universal taxonomy (w/ 194 classes). If we did not do so, we would need to specify 7*6=42 mappings (which would be unbelievably tedious and also fairly redundant) since we measure according to zero-shot cross-dataset generalization -- 7 training datasets with their own taxonomy, and each would need its own mapping to each of the 6 test sets.

By training each baseline that is trained on a single training dataset within the universal taxonomy, we are able to specify just 7+6=13 mappings [in this table](https://github.com/mseg-dataset/mseg-api/blob/master/mseg/class_remapping_files/MSeg_master.tsv) (each training dataset's taxonomy->universal taxonomy, and then universal taxonomy to each test dataset). I'll clarify this in the readme.

**Comment by achreff** [comment]
Thank your answer 
Could you upload hrnet_ocr files.

About PsPnet when i run the code i have this bug
![image](https://user-images.githubusercontent.com/15703187/83954555-86c00980-a84a-11ea-962e-d1257ff67ad0.png)

Have you any idea to solve this

**Comment by johnwlambert** [comment]
The pre-trained models we've uploaded are HRNet models (`arch: hrnet` in config). We have not provided any PSPNet models in this repo. Could you let me know which commands you are running?

**Comment by achreff** [comment]
I just changed the param arch : psp in the config file
Have you models pretrained on hrnet_ocr ?

**Comment by johnwlambert** [comment]
The pre-trained models we've uploaded are HRNet models (arch: hrnet in config). We have not provided any PSPNet models in this repo, since HRNet outperforms PSPNet in our past experiments.

We've provided two configs for inference, both of which specify the HRNetV2-W48 backbone:
[360p config](https://github.com/mseg-dataset/mseg-semantic/blob/master/mseg_semantic/config/test/default_config_360.yaml), [720p config](https://github.com/mseg-dataset/mseg-semantic/blob/master/mseg_semantic/config/test/default_config_720.yaml).
